################
### 공통 설정 ###
###############
server:
  port: 8081
  servlet:
    session:
      timeout: 30m
      cookie:
        name: ADMIN_SESSION
        http-only: true
        secure: false   # dev 프로필에서 true로 override
        same-site: Lax

spring:
  application:
    name: ngw-admin-back
  profiles:
    active: local

  # SQL 자동 초기화 비활성
  sql:
    init:
      mode: embedded

# === MyBatis 공통 설정 ===
mybatis:
  mapper-locations: classpath:/mybatis/**/*.xml
  type-aliases-package: com.nhbank.ngw.domain
  configuration:
    map-underscore-to-camel-case: true
    default-statement-timeout: 3
    jdbc-type-for-null: 'NULL'
    cache-enabled: false

ngw:
  base-url: http://ngw-internal.svc.cluster.local
  service-key: ${NGW_SERVICE_KEY:change-me}
  timeout:
    connect-millis: 2000
    read-millis: 3000

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    root: DEBUG
    com.nhbank.ngw: DEBUG
    sun.rmi: WARN
    javax.management.remote.rmi: WARN
    org.mybatis: DEBUG
    org.mybatis.spring: DEBUG

---

##################
### local 설정 ###
#################
spring:
  config:
    activate:
      on-profile: local

  datasource:
#    url: jdbc:h2:file:./.localdb/ngw;MODE=MySQL;DATABASE_TO_UPPER=false;AUTO_SERVER=TRUE # h2 파일형
    url: jdbc:h2:mem:ngw;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE # h2 메모리형
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

# 로컬 NGW 호출 오버라이드
ngw:
  base-url: http://localhost:8080
  timeout:
    connect-millis: 1500
    read-millis: 3000

---

################
### dev 설정 ###
###############
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/ngw?useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Seoul}
    driver-class-name: ${DB_DRIVER:com.mysql.cj.jdbc.Driver}
    username: ${DB_USERNAME:ngw}
    password: ${DB_PASSWORD:change-me}

# 운영 보안 쿠키 강화
server:
  servlet:
    session:
      cookie:
        secure: true
        same-site: Lax